stages:
  - build
  - deploy

build-image:
  stage: build
  image:
    name: registry.ihelse.net/gitlab/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
  - |
    echo "{\"auths\":{\"registry.ihelse.net\":{\"auth\":\"$(echo -n ${REGISTRY_USERNAME}:${REGISTRY_PASSWORD} | base64 -w 0)\"}}}" > /kaniko/.docker/config.json
  - |
    echo "${DEFAULT_CA_CERTS}" >> /kaniko/ssl/certs/ca-certificates.crt
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "Dockerfile"
      --destination "registry.ihelse.net/gitlab/nginx-hvikt:latest"

deploy:
  stage: deploy
  image: registry.ihelse.net/gitlab/kubectl-helm:1.27.8
  script:
    - kubectl config set-cluster bgo-k8s-0001 --server="https://bgo-k8s-0001.ihelse.net:8443"
    - kubectl config set clusters.bgo-k8s-0001.certificate-authority-data ${KUBERNETES_CLUSTER_CA}
    - kubectl config set-credentials demo-gitlabcicd --token="${KUBERNETES_SERVICE_ACCOUNT_TOKEN}"
    - kubectl config set-context default --cluster=bgo-k8s-0001 --user=demo-gitlabcicd
    - kubectl config use-context default
    - kubectl rollout restart -n my-ns deployment/webserver
